hics20_loda:
	tmux new-session -d -s "hics20_loda"
	tmux send-keys -t hics20_loda "cd ../../src && conda activate MxM && python -W ignore main.py -d loda -c ../configurations/classification/synthetic_datasets/group_g1/hics20_g1_config.json" ENTER

hics40_loda:
	tmux new-session -d -s "hics40_loda"
	tmux send-keys -t hics40_loda "cd ../../src && conda activate MxM && python -W ignore main.py -d loda -c ../configurations/classification/synthetic_datasets/group_g1/hics40_g1_config.json" ENTER

hics60_loda:
	tmux new-session -d -s "hics60_loda"
	tmux send-keys -t hics60_loda "cd ../../src && conda activate MxM && python -W ignore main.py -d loda -c ../configurations/classification/synthetic_datasets/group_g1/hics60_g1_config.json" ENTER

hics80_loda:
	tmux new-session -d -s "hics80_loda"
	tmux send-keys -t hics80_loda "cd ../../src && conda activate MxM && python -W ignore main.py -d loda -c ../configurations/classification/synthetic_datasets/group_g1/hics80_g1_config.json" ENTER

hics100_loda:
	tmux new-session -d -s "hics100_loda"
	tmux send-keys -t hics100_loda "cd ../../src && conda activate MxM && python -W ignore main.py -d loda -c ../configurations/classification/synthetic_datasets/group_g1/hics100_g1_config.json" ENTER

arrhythmia_loda:
	tmux new-session -d -s "arrhythmia_loda"
	tmux send-keys -t arrhythmia_loda "cd ../../src && conda activate MxM && python -W ignore main.py -d loda -c ../configurations/classification/real_datasets/arrhythmia015_config.json" ENTER

spectrometer_loda:
	tmux new-session -d -s "spectrometer_loda"
	tmux send-keys -t spectrometer_loda "cd ../../src && conda activate MxM && python -W ignore main.py -d loda -c ../configurations/classification/real_datasets/spectrometer01_config.json" ENTER

kc1_top5_loda:
	tmux new-session -d -s "kc1_top5_loda"
	tmux send-keys -t kc1_top5_loda "cd ../../src && conda activate MxM && python -W ignore main.py -d loda -c ../configurations/classification/real_datasets/kc1_top5_006_config.json" ENTER
