hics20_lof:
	tmux new-session -d -s "hics20_lof"
	tmux send-keys -t hics20_lof "cd ../../src && conda activate MxM && python -W ignore main.py -d lof -c ../configurations/classification/synthetic_datasets/group_g1/hics20_g1_config.json" ENTER

hics40_lof:
	tmux new-session -d -s "hics40_lof"
	tmux send-keys -t hics40_lof "cd ../../src && conda activate MxM && python -W ignore main.py -d lof -c ../configurations/classification/synthetic_datasets/group_g1/hics40_g1_config.json" ENTER

hics60_lof:
	tmux new-session -d -s "hics60_lof"
	tmux send-keys -t hics60_lof "cd ../../src && conda activate MxM && python -W ignore main.py -d lof -c ../configurations/classification/synthetic_datasets/group_g1/hics60_g1_config.json" ENTER

hics80_lof:
	tmux new-session -d -s "hics80_lof"
	tmux send-keys -t hics80_lof "cd ../../src && conda activate MxM && python -W ignore main.py -d lof -c ../configurations/classification/synthetic_datasets/group_g1/hics80_g1_config.json" ENTER

hics100_lof:
	tmux new-session -d -s "hics100_lof"
	tmux send-keys -t hics100_lof "cd ../../src && conda activate MxM && python -W ignore main.py -d lof -c ../configurations/classification/synthetic_datasets/group_g1/hics100_g1_config.json" ENTER

arrhythmia_lof:
	tmux new-session -d -s "arrhythmia_lof"
	tmux send-keys -t arrhythmia_lof "cd ../../src && conda activate MxM && python -W ignore main.py -d lof -c ../configurations/classification/real_datasets/arrhythmia015_config.json" ENTER

spectrometer_lof:
	tmux new-session -d -s "spectrometer_lof"
	tmux send-keys -t spectrometer_lof "cd ../../src && conda activate MxM && python -W ignore main.py -d lof -c ../configurations/classification/real_datasets/spectrometer01_config.json" ENTER

kc1_top5_lof:
	tmux new-session -d -s "kc1_top5_lof"
	tmux send-keys -t kc1_top5_lof "cd ../../src && conda activate MxM && python -W ignore main.py -d lof -c ../configurations/classification/real_datasets/kc1_top5_006_config.json" ENTER
