class FileNames:
    default_folder = '../results'
    predictions_folder = 'predictions'
    indices_folder = 'indices'
    configurations_folder = 'configurations'
    configurations_info_folder = 'configurations_info'
    configurations_perfs_folder = 'configuration_perfs'
    navigator_fname = 'navigator.json'
    detector_info_fname = 'detectors_info.json'
    train_test_indices_fname = 'train_test_indices.json'
    train_hold_out_indices_fname = 'train_holdout_inds.json'
    pseudo_samples_info = 'pseudo_samples_inds.json'
    best_models_bench_fname = 'models_benchmark.json'
    best_model_fname = 'best_model.json'
    baselines_explanations_fname = 'baseline_explanations.json'


class FileKeys:
    navigator_conf_path = 'config_path'
    navigator_original_dataset_path = 'original_dataset_path'
    navigator_original_data_results = 'original_data_results'
    navigator_train_hold_out_inds = 'train_holdout_inds'
    navigator_pseudo_samples_key = 'pseudo_samples'
    navigator_pseudo_samples_hold_out_data_key = 'hold_out_dataset_path'
    navigator_pseudo_sample_dir_key = 'dir'
    navigator_pseudo_samples_data_path = 'dataset_path'
    navigator_pseudo_samples_num_key = 'pseudo_samples_num'
    navigator_pseudo_samples_inds = 'pseudo_samples_inds_info'
    navigator_detector_info_path = 'detector_info'
    navigator_baseline = 'baselines'
    navigator_baselines_dir_key = 'baselines_dir'
    navigator_baselines_explanations_path = 'explanations_path'
    navigator_baselines_key = 'baselines'

