hics20_iforest:
	tmux new-session -d -s "hics20_iforest"
	tmux send-keys -t hics20_iforest "cd ../../src && conda activate MxM && python -W ignore main.py -d iforest -c ../configurations/classification/synthetic_datasets/group_g1/hics20_g1_config.json" ENTER

hics40_iforest:
	tmux new-session -d -s "hics40_iforest"
	tmux send-keys -t hics40_iforest "cd ../../src && conda activate MxM && python -W ignore main.py -d iforest -c ../configurations/classification/synthetic_datasets/group_g1/hics40_g1_config.json" ENTER

hics60_iforest:
	tmux new-session -d -s "hics60_iforest"
	tmux send-keys -t hics60_iforest "cd ../../src && conda activate MxM && python -W ignore main.py -d iforest -c ../configurations/classification/synthetic_datasets/group_g1/hics60_g1_config.json" ENTER

hics80_iforest:
	tmux new-session -d -s "hics80_iforest"
	tmux send-keys -t hics80_iforest "cd ../../src && conda activate MxM && python -W ignore main.py -d iforest -c ../configurations/classification/synthetic_datasets/group_g1/hics80_g1_config.json" ENTER

hics100_iforest:
	tmux new-session -d -s "hics100_iforest"
	tmux send-keys -t hics100_iforest "cd ../../src && conda activate MxM && python -W ignore main.py -d iforest -c ../configurations/classification/synthetic_datasets/group_g1/hics100_g1_config.json" ENTER

arrhythmia_iforest:
	tmux new-session -d -s "arrhythmia_iforest"
	tmux send-keys -t arrhythmia_iforest "cd ../../src && conda activate MxM && python -W ignore main.py -d iforest -c ../configurations/classification/real_datasets/arrhythmia015_config.json" ENTER

spectrometer_iforest:
	tmux new-session -d -s "spectrometer_iforest"
	tmux send-keys -t spectrometer_iforest "cd ../../src && conda activate MxM && python -W ignore main.py -d iforest -c ../configurations/classification/real_datasets/spectrometer01_config.json" ENTER

kc1_top5_iforest:
	tmux new-session -d -s "kc1_top5_iforest"
	tmux send-keys -t kc1_top5_iforest "cd ../../src && conda activate MxM && python -W ignore main.py -d iforest -c ../configurations/classification/real_datasets/kc1_top5_006_config.json" ENTER
